esiapp/urls.py
from django.urls import path, include
from . import views

app_name = "esiapp"

urlpatterns = [
    path('home/', views.homeAdmin, name='admin_home'),
    path('', views.homeUser, name="user_home"),
    path('login/', views.loginPage, name='login'),
    path('login/loggedin/', views.admin_login_custom, name="admin_login_custom"),
    path('logout/', views.Logout, name='logout'),
    path('nouvelle_publication/', views.new_publication, name='new_publication'),
    path('pubs/nouvelle_publication/', views.ajouter_publication, name="ajouter_publication"),
    path('delete/<int:item_id>/', views.delete_publication, name="delete_publication"),
    path('publications/edit/<int:item_id>/', views.edit_publication_page, name="edit_publication_page"),
    path('edit/<int:item_id>/', views.edit_publication, name="edit_publication"),
    path('publications/<int:item_id>/', views.display_publication_page_admin, name="display_publication_page_admin"),
    path('publications/<int:item_id>/commentaire/', views.ajouter_commentaire, name="ajouter_commentaire"),
    # path('publication/<int:item_id>/', views.display_publication_page_user, name="display_publication_page_user"),
    path('page_introuvable/', views.page_introuvable, name="page_introuvable"),
    path('catégories/', views.categorie_page, name="categorie_page"),
    path('categories/new/', views.ajouter_categorie, name="ajouter_categorie"),
    path('<int:item_id>/publications/', views.publications_page, name="publications_page"),
    path('jurys/', views.jurys_page, name="jurys_page"),
    path('jurys/new/', views.new_jury_page, name="new_jury_page"),
    path('jurys/new/jury', views.new_jury, name="new_jury"),
    path('files/download/<int:item_id>', views.download_file, name="download_file"),
]

project2cs_dpgr/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('esiapp.urls', namespace='esiapp')),
    #path('accounts/', include('django.contrib.auth.urls'))
    #path('', TemplateView.as_view(template_name='admin/home_page_admin.html'), name='home'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/categories_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <!-- Bootstraop script-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
            crossorigin="anonymous"></script>
    <title>Catégories</title>
</head>
<body>
{% if user.is_admin %}
    {% include 'admin/nav_bar.html' %}
{% elif user.is_teacher %}
    {% include 'user/nav_bar.html' %}
{% elif user.is_doctorant %}
    {% include 'nav_bar_doct.html' %}
{% endif %}
<hr class="dropdown-divider">

<!-- Website body -->
<div class="container-fluid"><h3>Liste des domaines</h3></div>
<div class="container-fluid py-3" style="background-color: #EEEEEE">
    <div class="container">
        <div class="row row-cols-3">
            {% for item, item1 in cat %}
                <div class="card col mb-3" style="background-color: #EEEEEE; border-width: 0px;">
                    <div class="card-header d-flex justify-content-center text-white" style="background-color: #0360b1">
                        <h4>{{ item.nom_categorie }}</h4>
                    </div>
                    <div class="card-body bg-white">
                        <h4 class="card-title d-flex justify-content-center m-3">Nombre de publications
                            : {{ item1 }}</h4>
                        <a href="#" type="button" class="btn d-flex justify-content-center m-3" style="color: #0360b1">
                            <h5>Afficher tout les messages</h5>
                        </a>
                    </div>
                </div>
            {% endfor %}
            {% if user.is_admin %}
                <div class="card col mb-3" style="background-color: #EEEEEE; border-width: 0px;">
                    <div class="card-header d-flex justify-content-center bg-white" style="color: #0360b1">
                        <h4>Nouvelle catégorie</h4>
                    </div>
                    <div class="card-body bg-white d-flex justify-content-center ">
                        <button class="btn m-3" style="color: #0360b1"
                                data-bs-toggle="modal" data-bs-target="#exampleModal9">
                            <img src="{% static 'icons/add_circle.svg' %}" width="100" height="100">
                        </button>
                        <!-- model togger -->
                        <form method="post" action="{% url 'esiapp:ajouter_categorie' %}">
                            <div class="modal fade" id="exampleModal9" tabindex="-1" aria-labelledby="exampleModalLabel"
                                 aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">List des emails :</h5>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                    aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">
                                            <div class="row">
                                                <div class="col">
                                                    <input type="text" class="form-control rounded-0  bg-white"
                                                           placeholder="Entrer le nom de la catégorie"
                                                           name="categorie_name"
                                                           style="border-color: #0360b1"
                                                           id="exampleFormControlTextarea1" rows="3">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="modal-footer d-flex justify-content-evenly">
                                            <button type="button" class="btn px-4 rounded-0"
                                                    data-bs-dismiss="modal"
                                                    style="color: #0360b1; border-color: #0360b1">
                                                Annuler
                                            </button>

                                            {% csrf_token %}
                                            <button type="submit" class="btn text-white px-4 rounded-0"
                                                    style="background-color: #3BB628">
                                                Ajouter
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
</div>
</body>
</html>

templates/jury_list_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <!-- Bootstraop script-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
            crossorigin="anonymous"></script>

    <title>jurys</title>
</head>
<body>
{% if user.is_admin %}
    {% include 'admin/nav_bar.html' %}
{% elif user.is_teacher %}
    {% include 'user/nav_bar.html' %}
{% elif user.is_doctorant %}
    {% include 'nav_bar_doct.html' %}
{% endif %}
<hr class="dropdown-divider">

<div class="container-fluid py-3" style="background-color: #EEEEEE">
    <div class="card">
        <div class="card-header text-white" style="background-color: #0360b1;">
            <h5>Liste jurys</h5>
        </div>
        <div class="card-body">
            <div class="row d-flex justify-content-between">
                <div class="col">
                    <form class="d-flex">
                        <input class="form-control border-primary rounded-0 w-50" type="search"
                               placeholder="Nom, prénom ou email d'enseignant">
                        <span class="input-group-append">
                    <button class="btn text-white border-primary rounded-0 border ms-2"
                            style="background-color: #0360b1"
                            type="submit">
                        Rechercher
                    </button>
                </span>
                    </form>
                </div>

                <div class="col d-flex justify-content-end">
                    {% if user.is_admin %}
                        <a class="btn bg-white border-primary rounded-0 border ms-2"
                           style="color: #0360b1; border-color: #0360b1"
                           href="{% url 'esiapp:new_jury_page' %}"
                           type="submit">
                            Ajouter un enseignant
                        </a>
                    {% endif %}
                </div>

            </div>
            <br>
            <!-- table of teachers -->
            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col" style="color: gray; font-size: 16px; font-weight: normal">Nom et prénom</th>
                    <th scope="col" style="color: gray; font-size: 16px; font-weight: normal">Adresse email</th>
                    <th scope="col" style="color: gray; font-size: 16px; font-weight: normal">N° de téléphone</th>
                    <th scope="col" style="color: gray; font-size: 16px; font-weight: normal">Wilaya</th>
                    <th scope="col" style="color: gray; font-size: 16px; font-weight: normal">Université</th>
                    <th scope="col" class="d-flex justify-content-center"
                        style="color: gray; font-size: 16px; font-weight: normal">Action
                    </th>
                </tr>
                </thead>
                <tbody>
                {% for jury in jurys %}
                    <tr>
                        <td>{{ jury.nom }} {{ jury.prenom }}</td>
                        <td>{{ jury.email }}</td>
                        <td>{{ jury.telephone }}</td>
                        <td>{{ jury.wilaya }}</td>
                        <td>{{ jury.university }}</td>
                        <td>
                            <div class="d-grid gap-4 d-md-flex align-items-center justify-content-center">
                                <a href="/publications/{{ pub.id }}" type="button" class="btn px-4 text-white rounded-0"
                                   style="background-color: #0360b1">
                                    Afficher
                                </a>
                                <a href="/publications/edit/{{ pub.id }}" type="button"
                                   class="btn text-white px-3 rounded-0"
                                   style="background-color: #3BB628">
                                    Modifier
                                </a>
                                <button type="button" class="btn text-white rounded-0" style="background-color: #F91717"
                                        data-bs-toggle="modal" data-bs-target="#exampleModal">
                                    Supprimer
                                </button>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <!-- footer -->
    <footer class="row mt-3">
        <small>
            <div class="fixed-bottom text-center text-white bg-dark col-lg-12">
                <address>
                    <strong>
                        Tous droits réservés - mentions légales - ESI 2021
                    </strong>
                </address>
            </div>
        </small>
    </footer>
</div>

</body>
</html>

templates/login_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <!-- Bootstraop script-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
            crossorigin="anonymous"></script>
    <title>Login</title>
</head>
<body style="background-image: url('https://wallpaperaccess.com/full/1876581.jpg'); height: 100vh">
<!-- Navigation bar -->
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #ffffff">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <div>
                <img src="{% static 'images/esi_logo3.png' %}" width="200" height="40" alt="">
                <!--<span style="">ESI Docs</span>-->
            </div>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
                aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-sm-end" id="navbarScroll">
            <button class="btn fs-4" type="submit">Contact-us</button>
        </div>
    </div>
</nav>
<!-- body -->
<div class="col bg-image d-flex py-4 justify-content-center align-items-center">
    <div class="container-md col-4 bg-white d-flex justify-content-center align-items-center">
        <div class="row p-5">
            <form class="px-4" action="{% url 'esiapp:admin_login_custom' %}" method="post">
                {% csrf_token %}
                <div class="d-flex justify-content-center"><img src="{% static 'images/esi_logo3.png' %}"
                                                                width="300" alt=""></div>
                <br>
                <div><p class="text-center fs-5">Bienvenu dans ESI Docs, plateforme pour les relations extérieures et
                    formation
                    continue.</p></div>
                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Adresse email :</label>
                    <input type="email" placeholder="Entrer l'adresse email"
                           name="email"
                           class="form-control rounded-0 "
                           id="exampleInputEmail1" aria-describedby="emailHelp">
                </div>
                <div class="mb-3">
                    <label for="exampleInputPassword1" class="form-label">Mot de passe :</label>
                    <input type="password" name="password" placeholder="Entrer le mot de passe" class="form-control rounded-0"
                           id="exampleInputPassword1">
                </div>
                <div class="mb-3 form-check">
                    <input type="checkbox" class="form-check-input" id="exampleCheck1">
                    <label class="form-check-label" for="exampleCheck1">Souviens de moi</label>
                </div>
                <div class="d-grid gap-2">
                    <button type="submit" class="btn text-white rounded-0 fs-4" style="background-color: #0360b1">
                        Connecter
                    </button>
                </div>
                <br>
            </form>

            <hr>
            <!-- Connect with google account -->
        </div>
        <div>

        </div>
    </div>
</div>
</body>
</html>

templates/nav_bar_doct.html
{% load static %}

<nav class="navbar navbar-expand-lg bg-white navbar-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <div>
                <img src="{% static 'images/esi_logo2.png' %}" style="vertical-align:middle"
                     width="200" height="60" alt="">
                <!--<span style="">ESI Docs</span>-->
            </div>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
                aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'esiapp:user_home' %}">Accueil</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'esiapp:categorie_page' %}">Domaines</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Contact Us</a>
                </li>
            </ul>
            <form class="d-flex w-50">
                <input class="form-control border-primary rounded-0" type="search" placeholder="Rechercher">
                <span class="input-group-append">
                    <button class="btn btn-outline-secondary bg-white border-primary border-start-0 rounded-0 border ms-n5"
                            type="button">
                        <img src="{% static 'icons/search.svg' %}">
                    </button>
                </span>
            </form>
        </div>
        </span>
        <div class="dropdown">
            <button class="btn" type="button" id="dropdownMenuButton2"
                    data-bs-toggle="dropdown" aria-expanded="false">
                <img src="{% static 'icons/circle_notifications.svg' %}" width="30" height="30">
            </button>
{#            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton2">#}
{#                <li><a class="dropdown-item" href="#">Action</a></li>#}
{#                <li><a class="dropdown-item" href="#">Another action</a></li>#}
{#                <li><a class="dropdown-item" href="#">Something else here</a></li>#}
{#                <li>#}
{#                    <hr class="dropdown-divider">#}
{#                </li>#}
{#                <li><a class="dropdown-item" href="#">Separated link</a></li>#}
{#            </ul>#}
        </div>
        <div>
            <div class="btn-group">
                <button type="button" class="btn dropdown-toggle text-white" data-bs-toggle="dropdown"
                        aria-expanded="false"
                        style="background-color: #0360b1;">
                    Mon compte
                </button>
                <ul class="dropdown-menu" style="right: 0; left: auto;">
                    <li><a class="dropdown-item" href="#">Mon profile</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="{% url 'esiapp:logout' %}">Deconnexion</a></li>
                </ul>
            </div>
        </div>
    </div>
</nav>

templates/page_404.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <!-- Bootstraop script-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
            crossorigin="anonymous"></script>
    <title>Title</title>
</head>
<body>
<div class="d-flex justify-content-center">
    <h1>404 !!!</h1>
</div>
</body>
</html>

templates/publications_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <!-- Bootstraop script-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
            crossorigin="anonymous"></script>
    <title>publications</title>
</head>
<body>
{% if user.is_admin %}
    {% include 'admin/nav_bar.html' %}
{% elif user.is_teacher %}
    {% include 'user/nav_bar.html' %}
{% elif user.is_doctorant %}
    {% include 'nav_bar_doct.html' %}
{% endif %}
<hr class="dropdown-divider">

<!-- Website body -->
<div class="container-fluid"><h3>Liste des domaines</h3></div>

<div class="container-fluid py-3" style="background-color: #EEEEEE">
    <div class="card">
        <div class="card-header text-white" style="background-color: #0360b1;">
            <h5>{{ cat_name }}</h5>
        </div>
        <div class="card-body">
            {% for pub in pubs %}
                <div class="row">
                    <div class="col">
                        <h4>{{ pub }}</h4>
                        <tbody>
                        <tr>
                            <td><strong>Publié par :</strong>{{ pub.send_By }}</td>
                            <td><strong>Ajouté le :</strong> {{ pub.date_ajout }}</td>
                            <td><strong>Date limite :</strong> {{ pub.date_limite }}</td>
                            <td><strong>Ajouté par :</strong> {{ pub.editeur }}</td>
                        </tr>
                        </tbody>
                    </div>
                    <div class="col">
                        <div class="d-grid gap-4 d-md-flex align-items-center justify-content-md-end">
                            <a href="/publications/{{ pub.id }}" type="button" class="btn px-4 text-white"
                               style="background-color: #0360b1">
                                Afficher
                            </a>
                            {% if user.is_admin %}
                            <a href="/publications/edit/{{ pub.id }}" type="button" class="btn text-white px-3"
                               style="background-color: #3BB628">
                                Modifier
                            </a>
                            <button type="button" class="btn text-white" style="background-color: #F91717"
                                    data-bs-toggle="modal" data-bs-target="#exampleModal">
                                Supprimer
                            </button>
                            {% endif %}
                            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                                 aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
                                    <div class="modal-content">
                                        <div class="modal-body d-flex justify-content-center">
                                            Vous êtes sur que vous voulez supprimé cette publication ?
                                        </div>
                                        <div class="modal-footer d-flex justify-content-evenly">
                                            <button type="button" class="btn px-4 rounded-0"
                                                    data-bs-dismiss="modal"
                                                    style="color: #0360b1; border-color: #0360b1">
                                                Annuler
                                            </button>
                                            <form method="post" action="{% url 'esiapp:delete_publication' pub.id %}">
                                                {% csrf_token %}
                                                <button type="submit"
                                                        class="btn text-white px-4 rounded-0"
                                                        style="background-color: red">
                                                    Supprimer
                                                </button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr class="dropdown-divider">
                </div>
            {% endfor %}
        </div>
    </div>
</div>

<!-- footer -->
<footer class="row mt-3">
    <small>
        <div class="fixed-bottom text-center text-white bg-dark col-lg-12">
            <address>
                <strong>
                    Tous droits réservés - mentions légales - ESI 2021
                </strong>
            </address>
        </div>
    </small>
</footer>
</body>
</html>