esiapp/urls.py
from django.urls import path, include
from . import views

app_name = "esiapp"

urlpatterns = [
    path('home/', views.homeAdmin, name='admin_home'),
    path('', views.homeUser, name="user_home"),
    path('login/', views.loginPage, name='login'),
    path('login/loggedin/', views.admin_login_custom, name="admin_login_custom"),
    path('logout/', views.Logout, name='logout'),
    path('nouvelle_publication/', views.new_publication, name='new_publication'),
    path('pubs/nouvelle_publication/', views.ajouter_publication, name="ajouter_publication"),
    path('delete/<int:item_id>/', views.delete_publication, name="delete_publication"),
    path('publications/edit/<int:item_id>/', views.edit_publication_page, name="edit_publication_page"),
    path('edit/<int:item_id>/', views.edit_publication, name="edit_publication"),
    path('publications/<int:item_id>/', views.display_publication_page_admin, name="display_publication_page_admin"),
    path('publications/<int:item_id>/commentaire/', views.ajouter_commentaire, name="ajouter_commentaire"),
    # path('publication/<int:item_id>/', views.display_publication_page_user, name="display_publication_page_user"),
    path('page_introuvable/', views.page_introuvable, name="page_introuvable"),
    path('catégories/', views.categorie_page, name="categorie_page"),
    path('categories/new/', views.ajouter_categorie, name="ajouter_categorie"),
    path('<int:item_id>/publications/', views.publications_page, name="publications_page"),
    path('jurys/', views.jurys_page, name="jurys_page"),
    path('jurys/new/', views.new_jury_page, name="new_jury_page"),
    path('jurys/new/jury', views.new_jury, name="new_jury"),
    path('files/download/<int:item_id>', views.download_file, name="download_file"),
]

project2cs_dpgr/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('esiapp.urls', namespace='esiapp')),
    #path('accounts/', include('django.contrib.auth.urls'))
    #path('', TemplateView.as_view(template_name='admin/home_page_admin.html'), name='home'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/user/display_publication_user.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <!-- Bootstraop script-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
            crossorigin="anonymous"></script>
    <title>Détails publication</title>
    <title>Title</title>
</head>
<body>
{% include 'user/nav_bar.html' %}
</body>
</html>

templates/user/home_page_user.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <!-- Bootstraop script-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
            crossorigin="anonymous"></script>
    <title>Accueil utilisateur</title>
</head>
<body>
{% if user.is_teacher %}
    {% include 'user/nav_bar.html' %}
{% elif user.is_doctorant %}
    {% include 'nav_bar_doct.html' %}
{% endif %}
<hr class="dropdown-divider">

<!-- Website body -->
<div class="container-fluid"><h2>Liste des domaines</h2></div>

<!-- Container offres de bources -->
<div class="container-fluid py-3" style="background-color: #EEEEEE">
    <div class="card">
        <div class="card-header text-white" style="background-color: #0360b1;">
            <h5>Offres de bources</h5>
        </div>
        <div class="card-body">
            {% for pub in pub_offres_brouces %}
                <div class="row">
                    <div class="col">
                        <h4>{{ pub }}</h4>
                        <tbody>
                        <tr>
                            <td><strong>Publié par :</strong> {{ pub.send_By }}</td>
                            <td><strong>Date limite :</strong> {{ pub.date_ajout }}</td>
                            <td><strong>Ajouté par :</strong>{{ pub.editeur }}</td>
                        </tr>
                        </tbody>
                    </div>
                    <div class="col">
                        <div class="d-grid gap-4 d-md-flex align-items-center justify-content-md-end">
                            <a href="/publications/{{ pub.id }}" type="button" class="btn px-4 rounded-0"
                               style="color: #0360b1; border-color: #0360b1;">
                                Afficher
                            </a>
                        </div>
                    </div>
                    <hr class="dropdown-divider">
                </div>
            {% endfor %}
            <div class="d-grid gap-2">
                <a
                        {% if pub_offres_brouces %}
                            href="{% url 'esiapp:publications_page' pub_offres_brouces.0.Categorie.id %}"
                        {% else %}
                            href="#"
                        {% endif %}
                            class="btn" type="button" style="color: #0360b1"><h5>Afficher tout les
                    messages</h5></a>
            </div>
        </div>
    </div>
    <!-- div for 2 categories -->
    <div class="row">
        <!-- category 2: entreprise -->
        <div class="col">
            <div class="py-3" style="background-color: #EEEEEE">
                <div class="card">
                    <div class="card-header text-white" style="background-color: #0360b1;">
                        <h5>Entreprises</h5>
                    </div>
                    <div class="card-body">
                        {% for pub in pub_entreprise %}
                            <div class="row">
                                <div class="col">
                                    <h4>{{ pub }}</h4>
                                    <tbody>
                                    <tr>
                                        <td><strong>Publié par :</strong> {{ pub.send_By }}</td>
                                        <td><strong>Date limite :</strong> {{ pub.date_limite }}</td>
                                        <td><strong>Ajouté par :</strong> {{ pub.editeur }}</td>
                                    </tr>
                                    </tbody>
                                </div>
                                <div class="col-2">
                                    <div class="d-grid gap-4 d-md-flex align-items-center justify-content-md-end">
                                        <a href="/publications/{{ pub.id }}">
                                            <img src="{% static 'icons/display_icon.svg' %}" width="40" height="40">
                                        </a>
                                    </div>
                                </div>
                                <hr class="dropdown-divider">
                            </div>
                        {% endfor %}
                        <div class="d-grid gap-2">
                            <a
                                    {% if pub_entreprise %}
                                        href="{% url 'esiapp:publications_page' pub_entreprise.0.Categorie.id %}"
                                    {% else %}
                                        href="#"
                                    {% endif %}
                                        class="btn" type="button" style="color: #0360b1"><h5>Afficher tout les
                                messages</h5></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- category 3: projets de recherche -->
        <div class="col">
            <div class="py-3" style="background-color: #EEEEEE">
                <div class="card">
                    <div class="card-header text-white" style="background-color: #0360b1;">
                        <h5>Projets de recherches</h5>
                    </div>
                    <div class="card-body">
                        {% for pub in pub_projet_rech %}
                            <div class="row">
                                <div class="col">
                                    <h4>{{ pub }}</h4>
                                    <tbody>
                                    <tr>
                                        <td><strong>Publié par :</strong> {{ pub.send_By }}</td>
                                        <td><strong>Date limite :</strong> {{ pub.date_limite }}</td>
                                        <td><strong>Ajouté par :</strong> {{ pub.editeur }}</td>
                                    </tr>
                                    </tbody>
                                </div>
                                <div class="col-2">
                                    <div class="d-grid gap-4 d-md-flex align-items-center justify-content-md-end">
                                        <a href="/publications/{{ pub.id }}">
                                            <img src="{% static 'icons/display_icon.svg' %}" width="40" height="40">
                                        </a>

                                    </div>
                                </div>
                                <hr class="dropdown-divider">
                            </div>
                        {% endfor %}
                        <div class="d-grid gap-2">
                            <a
                                    {% if pub_projet_rech %}
                                        href="{% url 'esiapp:publications_page' pub_projet_rech.0.Categorie.id %}"
                                    {% else %}
                                        href="#"
                                    {% endif %}
                                        class="btn" type="button" style="color: #0360b1"><h5>Afficher tout les
                                messages</h5></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- div for 2 categories (4&5)-->
    <div class="row">
        <!-- category 4: PRFU -->
        <div class="col">
            <div class="py-3" style="background-color: #EEEEEE">
                <div class="card">
                    <div class="card-header text-white" style="background-color: #0360b1;">
                        <h5>PRFU</h5>
                    </div>
                    <div class="card-body">
                        {% for pub in pub_prfu %}
                            <div class="row">
                                <div class="col">
                                    <h4>{{ pub }}</h4>
                                    <tbody>
                                    <tr>
                                        <td><strong>Publié par :</strong>{{ pub.send_By }}</td>
                                        <td><strong>Date limite :</strong> {{ pub.date_limite }}</td>
                                        <td><strong>Ajouté par :</strong> {{ pub.editeur }}</td>
                                    </tr>
                                    </tbody>
                                </div>
                                <div class="col-2">
                                    <div class="d-grid gap-4 d-md-flex align-items-center justify-content-md-end">
                                        <a href="/publications/{{ pub.id }}">
                                            <img src="{% static 'icons/display_icon.svg' %}" width="40" height="40">
                                        </a>

                                    </div>
                                </div>
                                <hr class="dropdown-divider">
                            </div>
                        {% endfor %}
                        <div class="d-grid gap-2">
                            <a
                                    {% if pub_prfu %}
                                        href="{% url 'esiapp:publications_page' pub_prfu.0.Categorie.id %}"
                                    {% else %}
                                        href="#"
                                    {% endif %}
                                        class="btn" type="button" style="color: #0360b1"><h5>Afficher tout les
                                messages</h5></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- category 5: Autres -->
        <div class="col">
            <div class="py-3" style="background-color: #EEEEEE">
                <div class="card">
                    <div class="card-header text-white" style="background-color: #0360b1;">
                        <h5>Autres</h5>
                    </div>
                    <div class="card-body">
                        {% for pub in pub_autres %}
                            <div class="row">
                                <div class="col">
                                    <h4>{{ pub }}</h4>
                                    <tbody>
                                    <tr>
                                        <td><strong>Publié par :</strong>{{ pub.send_By }}</td>
                                        <td><strong>Date limite :</strong> {{ pub.date_limite }}</td>
                                        <td><strong>Ajouté par :</strong> {{ pub.editeur }}</td>
                                    </tr>
                                    </tbody>
                                </div>
                                <div class="col-2">
                                    <div class="d-grid gap-4 d-md-flex align-items-center justify-content-md-end">
                                        <a href="/publications/{{ pub.id }}">
                                            <img src="{% static 'icons/display_icon.svg' %}" width="40" height="40">
                                        </a>

                                    </div>
                                </div>
                                <hr class="dropdown-divider">
                            </div>
                        {% endfor %}
                        <div class="d-grid gap-2">
                            <div class="d-grid gap-2">
                                <a
                                        {% if pub_autres %}
                                            href="{% url 'esiapp:publications_page' pub_autres.0.Categorie.id %}"
                                        {% else %}
                                            href="#"
                                        {% endif %}
                                            class="btn" type="button" style="color: #0360b1"><h5>Afficher tout les
                                    messages</h5></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- footer -->
<footer class="row mt-3">
    <small>
        <div class="fixed-bottom text-center text-white bg-dark col-lg-12">
            <address>
                <strong>
                    Tous droits réservés - mentions légales - ESI 2021
                </strong>
            </address>
        </div>
    </small>
</footer>
</body>
</html>

templates/user/nav_bar.html
{% load static %}

<nav class="navbar navbar-expand-lg bg-white navbar-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <div>
                <img src="{% static 'images/esi_logo2.png' %}" style="vertical-align:middle"
                     width="200" height="60" alt="">
                <!--<span style="">ESI Docs</span>-->
            </div>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
                aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'esiapp:admin_home' %}">Accueil</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'esiapp:categorie_page' %}">Domaines</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Contact Us</a>
                </li>
            </ul>
            <form class="d-flex w-50">
                <input class="form-control border-primary rounded-0" type="search" placeholder="Rechercher">
                <span class="input-group-append">
                    <button class="btn btn-outline-secondary bg-white border-primary border-start-0 rounded-0 border ms-n5"
                            type="button">
                        <img src="{% static 'icons/search.svg' %}">
                    </button>
                </span>
            </form>
        </div>
        </span>
        <div class="dropdown">
            <button class="btn" type="button" id="dropdownMenuButton2"
                    data-bs-toggle="dropdown" aria-expanded="false">
                <img src="{% static 'icons/circle_notifications.svg' %}" width="30" height="30">
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton2">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
                <li>
                    <hr class="dropdown-divider">
                </li>
                <li><a class="dropdown-item" href="#">Separated link</a></li>
            </ul>
        </div>
        <div>
            <div class="btn-group">
                <button type="button" class="btn dropdown-toggle text-white" data-bs-toggle="dropdown"
                        aria-expanded="false"
                        style="background-color: #0360b1;">
                    Mon compte
                </button>
                <ul class="dropdown-menu" style="right: 0; left: auto;">

                    <li><a class="dropdown-item" href="#">Mon profile</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="#">liste des jurys</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="{% url 'esiapp:logout' %}">Deconnexion</a></li>
                </ul>
            </div>
        </div>
    </div>
</nav>